; Author: Michael Garcia, M&E Design
; License: MIT
; Date: 2026-04-17
; Contact: michael@mandedesign.studio
; Website: https://mandedesign.studio

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
